### ISSUE TITLE
Just use VM, not docker

### ISSUE THREAD

**Issue by jjangga0214** [veggiemonk/skip-commit#2]
I guess this would consume much time.

https://github.com/veggiemonk/skip-commit/blob/12d2e003f462c2b9902804159707172bed6e4872/Dockerfile#L14-L16

According to https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts, VMs already have git preinstalled, so docker is not needed.

**Comment by JaKXz** [comment]
So would we just want to use the `entrypoint.sh` file in our github actions folder and just run it as a step?

**Comment by veggiemonk** [comment]
I think you can just use bash now.

```bash
# Get last commit message
readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
echo "last commit log: $last_commit_log"

readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

if [[ "$filter_count" -eq 0 ]]; then
  echo "all good, continue"
else
  echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
  exit 78
fi
```
