### ISSUE TITLE
Skip-ci not working

### ISSUE THREAD

**Issue by mehulagg** [veggiemonk/skip-commit#4]
My commit msg contains [skip-ci] but its not stopping the build.
![20191115_080210](https://user-images.githubusercontent.com/53606356/68912541-70ebd980-077e-11ea-9da1-ceb0b0f9957d.jpg)

![Screenshot_20191115-081446_Chrome](https://user-images.githubusercontent.com/53606356/68913046-0dfb4200-0780-11ea-8b55-bbc72f24cb81.jpg)

**Comment by veggiemonk** [comment]
hi @mehulagg,

It just use `grep` so putting non alphanumeric characters in the `COMMIT_FILTER` won't work.
See for other example https://tldr.ostera.io/grep

Just remove `[` and `]` from the `COMMIT_FILTER` like this :
```yaml
env:
  COMMIT_FILTER: "skip-ci"
```
and it will work.

**Comment by veggiemonk** [comment]
It is now fixed in the example. Sorry for the confusion.
